apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
      - name: webpage
        image: fabricioveronez/pagina-exemplo:blue
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: webpage
spec:
  selector:
    app: webpage
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webpage-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: webpage.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webpage
            port:
              number: 80
